### ISSUE TITLE
Building on Windows 64 bit

### ISSUE THREAD

**Issue by josephernest** [Falcosoft/ASIO2WASAPI#1]
Thanks for your fork.
What are the requirements to build it? Which is the smallest MSVC++ version that I can use to build it?

**Comment by Falcosoft** [comment]
Hi,
Since I have not modified the original solution and project files in theory it could be compiled even with VS 2010.
I'm using VS 2019 to compile it so in practice let's say it's VS 2019 :). 
Do you have any specific problems with compiling?
